tap "heroku/brew"
tap "crisidev/chunkwm"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"
brew "aacgain"
brew "ansible"
brew "python"
brew "asciinema"
brew "bash"
brew "bash-completion"
brew "cheat"
brew "coreutils"
brew "duti"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "gdb"
brew "git"
brew "git-lfs"
brew "gnu-tar"
brew "gnupg"
brew "gpg-agent"
brew "node"
brew "heroku"
brew "mas"
brew "neovim"
brew "nmap"
brew "nvm"
brew "p7zip"
brew "picocom"
brew "pinentry-mac"
brew "qpdf"
brew "reattach-to-user-namespace"
brew "smartmontools"
brew "source-highlight"
brew "stow"
brew "tmux"
brew "unrar"
brew "vim"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "crisidev/chunkwm/chunkwm"
brew "koekeishiya/formulae/khd"
cask "alfred"
cask "android-file-transfer"
cask "android-sdk"
cask "blackscreen-screensaver"
cask "burn"
cask "cevelop"
cask "dash"
cask "docker"
cask "google-backup-and-sync"
cask "google-chrome"
cask "handbrake"
cask "intellij-idea-ce"
cask "iterm2"
cask "java"
cask "keepingyouawake"
cask "mactex"
cask "microsoft-office"
cask "paragon-extfs"
cask "paragon-ntfs"
cask "parallels"
cask "postgres"
cask "skype"
cask "spotify"
cask "staruml"
cask "teamviewer"
cask "visual-studio-code"
cask "vlc"
cask "wireshark"
cask "caskroom/fonts/font-awesome-terminal-fonts"
cask "caskroom/versions/java8"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Enpass", id: 732710998
mas "iMovie", id: 408981434
mas "Microsoft Remote Desktop", id: 715768417
mas "Moodle Desktop", id: 1255924440
mas "Telegram", id: 747648890
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
