---
system:
  hostname: "bumblebee"
  setup_path: "$HOME/.setup"
  keyboard_layout: "LogitechSwissGerman"
  dotfiles_url: "https://gitlab.com/cynja/dotfiles.git"
  dotfiles_script: "init.sh"
  default_shell: "/bin/zsh"
  username: "cynja"
  time:
    zone: "Europe/Zurich"
    server: "ch.pool.ntp.org"

packages:
  pip:
    - beets
    # Enable fingerprinting support in beets
    - pyacoustid
    - virtualenvwrapper
    - virtualenv

apps:
  # Check /Applications/*.app for a list of apps
  disabled:
    - "DVD Player"
    - Dashboard
    - Facetime
    - "Image Capture"
    - Launchpad
    - Mail
    - Maps
    - Messages
    - Notes
    - Photos
    - "QuickTime Player"
    - Reminders
    - Safari
    - Siri
    - Stickies
    - TextEdit
    - iBooks
    - iTunes