---
system:
  hostname: "bumblebee"
  username: "cynja"
  dotfiles: "git@github.com:cynja/dotfiles.git"
vm:
  hostname: "ratchet"
  packages:
    chocolatey:
      - origin
      - visualstudio2017community
      - 7zip
  settings:
    # Privacy settings
    - DisableTelemetry
    - DisableWiFiSense
    - DisableSmartScreen
    - DisableWebSearch
    - DisableAppSuggestions
    - DisableBackgroundApps
    - DisableLockScreenSpotlight
    - DisableLocationTracking
    - DisableMapUpdates
    - DisableFeedback
    - DisableAdvertisingID
    - DisableCortana
    - DisableErrorReporting
    - SetP2PUpdateLocal
    - DisableAutoLogger
    - DisableDiagTrack
    - DisableWAPPush
    # Security settings
    - DisableAdminShares
    - DisableSMB1
    - SetCurrentNetworkPrivate
    - SetUnknownNetworksPublic
    - DisableHomeGroups
    - DisableSharedExperiences
    - DisableRemoteAssistance
    - DisableAutoplay
    - DisableAutorun
    # System settings
    - DisableDefragmentation
    - DisableOneDrive
    - DisableXboxFeatures
    - DisableAdobeFlash
    - EnableF8BootMenu
    # Remove bloat
    - UninstallOneDrive
    - UninstallMsftBloat
    - UninstallThirdPartyBloat
    - UninstallWindowsStore
    - UninstallMediaPlayer
    - UninstallWorkFolders
    # UI settings
    - DisableActionCenter
    - DisableLockScreen
    - HideNetworkFromLockScreen
    - ShowFileOperationsDetails
    - DisableFileDeleteConfirm
    - HideTaskbarSearchBox
    - HideTaskView
    - ShowSmallTaskbarIcons
    - HideTaskbarPeopleIcon
    - ShowTrayIcons
    - HideKnownExtensions
    - HideHiddenFiles
    - ShowSyncNotifications
    - HideRecentShortcuts
    - SetExplorerThisPC
    - HideThisPCFromDesktop
    - HideUserFolderFromDesktop
    - ShowDesktopInExplorer
    - HideDocumentsFromThisPC
    - ShowDocumentsInExplorer
    - HideDownloadsFromThisPC
    - ShowDownloadsInExplorer
    - HideMusicFromThisPC
    - HidePicturesInExpolorer
    - HidePicturesFromThisPC
    - HideVideosInExplorer
    - HideVideosFromThisPC
    - Hide3DObjectsFromExplorer
    - Hide3DObjectsFromThisPC
    - DisableThumbnails
    - DisableThumbsDB