---
all:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local
    ratchet:
      ansible_user: "cynja"
      ansible_host: 10.211.55.3
      ansible_port: 5986
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore